name: DCO

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  signoff:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: DCO-org/action@be050f40fde33ca765caf993a39f1ddb6f0a1d3 # v1.2.0
